# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: GREW
  dataset_root: path/to/GREW-pkl
  dataset_partition: ./datasets/GREW/GREW.json
  num_workers: 8
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: GREW

evaluator_cfg:
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 10000
  save_name: GaitGL
  eval_func: evaluate_real_scene #GREW_submission # identification_real_scene # identification_GREW_submission
  sampler:
    batch_size: 4
    sample_type: all_ordered
    type: InferenceSampler
  transform:
    - img_w: 64
      occlude_bounds: [0.2, 0.5]
      type: RandomOccludeTransform    

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: true
    log_prefix: softmax

model_cfg:
  model: GaitGL_occ_aware_guided_lin
  channels: [32, 64, 128, 256]
  class_num: 20000
  occ_detector_path: /path/to/occlusion_detector.pth
  occ_dim: 64

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 150000
    - 200000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  wandb: False
  with_test: true
  log_iter: 1000
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: GaitGL_occ_aware_guided_lin
  sync_BN: true
  total_iter: 250000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32
      - 4
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
      - img_w: 64
        occlude_bounds: [0.2, 0.5]
        type: RandomOccludeTransform    
